/*
LLM usage: this test file was generated by deepseek-v4-pro with manual modifications.
*/

package engine

import (
	"bytes"
	"context"
	"log/slog"
	"net/netip"
	"os"
	"sync"
	"testing"
	"time"

	"github.com/HT4w5/flux/pkg/cache"
	"github.com/HT4w5/flux/pkg/dto"
	"go.yaml.in/yaml/v3"
)

// --------------- stubs ---------------

// stubJail implements Jail and captures added bans for test inspection.
type stubJail struct {
	bans []dto.BanRecord
	mu   sync.Mutex
}

func newStubJail() *stubJail {
	return &stubJail{bans: make([]dto.BanRecord, 0)}
}

func (j *stubJail) Start() error { return nil }
func (j *stubJail) Close() error { return nil }

func (j *stubJail) Add(_ context.Context, b *dto.BanRecord) error {
	j.mu.Lock()
	defer j.mu.Unlock()
	j.bans = append(j.bans, *b)
	return nil
}

func (j *stubJail) Del(_ context.Context, _ netip.Addr) error { return nil }

func (j *stubJail) List(_ context.Context) ([]dto.BanRecord, error) {
	j.mu.Lock()
	defer j.mu.Unlock()
	out := make([]dto.BanRecord, len(j.bans))
	copy(out, j.bans)
	return out, nil
}

func (j *stubJail) Compile(_ context.Context) ([]dto.BanRule, error) {
	return nil, nil
}

func (j *stubJail) banCount() int {
	j.mu.Lock()
	defer j.mu.Unlock()
	return len(j.bans)
}

func (j *stubJail) lastBan() *dto.BanRecord {
	j.mu.Lock()
	defer j.mu.Unlock()
	if len(j.bans) == 0 {
		return nil
	}
	cp := j.bans[len(j.bans)-1]
	return &cp
}

// stubFileSizeIndex implements FileSizeIndex.
type stubFileSizeIndex struct {
	sizes map[string]int64
}

func newStubFileSizeIndex(sizes map[string]int64) *stubFileSizeIndex {
	return &stubFileSizeIndex{sizes: sizes}
}

func (s *stubFileSizeIndex) GetSize(path []byte) (int64, bool) {
	sz, ok := s.sizes[string(path)]
	return sz, ok
}

// --------------- helpers ---------------

// readYAMLChains reads a YAML file into []ChainConfig.
// Each top-level item must have the shape of ChainConfig.
func readYAMLChains(t *testing.T, path string) []ChainConfig {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read file %s: %v", path, err)
	}
	var chains []ChainConfig
	if err := yaml.Unmarshal(data, &chains); err != nil {
		t.Fatalf("unmarshal %s: %v", path, err)
	}
	return chains
}

// renameMainTo picks the chain with name=from and renames it to "main".
// Other chains are returned unchanged.  This lets YAML files declare their
// entrypoint chain with a human-readable name.
func renameMainTo(chains []ChainConfig, from string) []ChainConfig {
	out := make([]ChainConfig, len(chains))
	copy(out, chains)
	for i := range out {
		if out[i].Name == from {
			out[i].Name = "main"
			return out
		}
	}
	return out
}

// newRequest builds a dto.Request with sensible defaults that can be
// overridden via the opts functional-argument list.
func newRequest(ip netip.Addr, opts ...func(*dto.Request)) dto.Request {
	r := dto.Request{
		Time:     time.Date(2025, 6, 1, 12, 0, 0, 0, time.UTC),
		Client:   ip,
		Server:   netip.MustParseAddr("192.168.1.1"),
		Method:   "GET",
		URL:      "/index.html",
		Host:     "example.com",
		Status:   200,
		Sent:     1024,
		Duration: 10 * time.Millisecond,
		Agent:    "Mozilla/5.0",
	}
	for _, o := range opts {
		o(&r)
	}
	return r
}

// --------------- tests: flow control ---------------

func TestFlowControl(t *testing.T) {
	jail := newStubJail()
	fsi := newStubFileSizeIndex(map[string]int64{})

	chains := readYAMLChains(t, "testdata/flow_control.yaml")

	tests := []struct {
		chainName  string
		wantBans   int
		wantBanDur time.Duration
		desc       string
	}{
		{"flow-stop", 0, 0, "STOP prevents subsequent rules"},
		{"flow-continue", 1, 30 * time.Minute, "CONTINUE allows following rule"},
		{"flow-goto", 1, 45 * time.Minute, "GOTO enters target chain and does not return"},
		{"flow-jump", 2, 1 * time.Hour, "JUMP enters target chain then resumes"},
		{"flow-goto-early-stop", 0, 0, "GOTO + STOP in target prevents later rules"},
		{"flow-jump-chain-continue", 2, 20 * time.Minute, "two JUMPs execute both sub-chains"},
	}

	for _, tt := range tests {
		t.Run(tt.desc, func(t *testing.T) {
			jail.bans = jail.bans[:0]

			// channel is now engine-owned
			re := New(
				WithJail(jail),
				WithFileSizeIndex(fsi),
				WithCache(cache.NewCCacheCache(100)),
				WithNumWorkers(1),
			)

			cfg := renameMainTo(chains, tt.chainName)
			if err := re.Start(cfg); err != nil {
				t.Fatalf("Start: %v", err)
			}
			defer re.Shutdown()

			req := newRequest(netip.MustParseAddr("10.0.0.1"))
			re.SendChan() <- req
			time.Sleep(100 * time.Millisecond)

			if got := jail.banCount(); got != tt.wantBans {
				t.Errorf("bans: got %d, want %d", got, tt.wantBans)
			}
			if tt.wantBanDur > 0 {
				lb := jail.lastBan()
				if lb == nil {
					t.Fatal("expected a ban but none recorded")
				}
				// Durations may vary slightly due to time.Now(), check approximate
				if d := time.Until(lb.ExpiresAt); d < tt.wantBanDur-5*time.Second || d > tt.wantBanDur+5*time.Second {
					t.Errorf("ban duration ~ %v, want ~ %v", d, tt.wantBanDur)
				}
			}
		})
	}
}

// --------------- tests: expression matching ---------------

func TestExpressionMatching(t *testing.T) {
	jail := newStubJail()
	fsi := newStubFileSizeIndex(map[string]int64{})

	chains := readYAMLChains(t, "testdata/expr_matching.yaml")

	addr10 := netip.MustParseAddr("10.0.0.5")
	addr99 := netip.MustParseAddr("99.99.99.99")
	addr172 := netip.MustParseAddr("172.16.0.1")

	baseTime := time.Date(2025, 1, 1, 0, 0, 0, 0, time.UTC)

	tests := []struct {
		chainName string
		req       dto.Request
		wantBans  int
		desc      string
	}{
		// ALL / NONE
		{"expr-all", newRequest(addr10), 1, "ALL always matches"},
		{"expr-none", newRequest(addr10), 1, "NONE skips first rule, ALL matches fallback"},

		// METHOD
		{"expr-method-get", newRequest(addr10, withMethod("GET")), 1, "METHOD: GET"},
		{"expr-method-get", newRequest(addr10, withMethod("POST")), 0, "METHOD: GET — POST should not match"},
		{"expr-method-post", newRequest(addr10, withMethod("POST")), 1, "METHOD: POST"},

		// URL
		{"expr-url-exact", newRequest(addr10, withURL("/admin/login")), 1, "URL exact match"},
		{"expr-url-exact", newRequest(addr10, withURL("/admin/other")), 0, "URL exact mismatch"},
		{"expr-url-prefix", newRequest(addr10, withURL("/admin/secret")), 1, "URL-PREFIX match"},
		{"expr-url-prefix", newRequest(addr10, withURL("/api/")), 0, "URL-PREFIX mismatch"},
		{"expr-url-prefix-set", newRequest(addr10, withURL("/api")), 1, "URL-PREFIX-SET mismatch"},
		{"expr-url-prefix-set", newRequest(addr10, withURL("/admin")), 1, "URL-PREFIX-SET mismatch"},
		{"expr-url-prefix-set", newRequest(addr10, withURL("/.well-known")), 1, "URL-PREFIX-SET mismatch"},
		{"expr-url-prefix-set", newRequest(addr10, withURL("/static")), 1, "URL-PREFIX-SET mismatch"},
		{"expr-url-prefix-set", newRequest(addr10, withURL("/admin/login")), 1, "URL-PREFIX-SET mismatch"},
		{"expr-url-prefix-set", newRequest(addr10, withURL("/auth")), 0, "URL-PREFIX-SET mismatch"},
		{"expr-url-prefix-set", newRequest(addr10, withURL("/.well-kn")), 0, "URL-PREFIX-SET mismatch"},
		{"expr-url-prefix-set", newRequest(addr10, withURL("/.well-known/geodata.json")), 1, "URL-PREFIX-SET mismatch"},
		{"expr-url-suffix", newRequest(addr10, withURL("/wp-login.php")), 1, "URL-SUFFIX match"},
		{"expr-url-suffix", newRequest(addr10, withURL("/wp-login.html")), 0, "URL-SUFFIX mismatch"},
		{"expr-url-keyword", newRequest(addr10, withURL("/auth/login")), 1, "URL-KEYWORD match"},
		{"expr-url-keyword", newRequest(addr10, withURL("/home")), 0, "URL-KEYWORD mismatch"},

		{"expr-url-set", newRequest(addr10, withURL("/api")), 1, "URL-SET mismatch"},
		{"expr-url-set", newRequest(addr10, withURL("/admin")), 1, "URL-SET mismatch"},
		{"expr-url-set", newRequest(addr10, withURL("/.well-known")), 1, "URL-SET mismatch"},
		{"expr-url-set", newRequest(addr10, withURL("/static")), 1, "URL-SET mismatch"},
		{"expr-url-set", newRequest(addr10, withURL("/admin/login")), 1, "URL-SET mismatch"},
		{"expr-url-set", newRequest(addr10, withURL("/auth")), 0, "URL-SET mismatch"},
		{"expr-url-set", newRequest(addr10, withURL("/.well-kn")), 0, "URL-SET mismatch"},
		{"expr-url-set", newRequest(addr10, withURL("/.well-known/geodata.json")), 0, "URL-SET mismatch"},

		{"expr-url-map", newRequest(addr10, withURL("/api")), 1, "URL-MAP mismatch"},
		{"expr-url-map", newRequest(addr10, withURL("/admin")), 1, "URL-MAP mismatch"},
		{"expr-url-map", newRequest(addr10, withURL("/auth")), 0, "URL-MAP mismatch"},
		{"expr-url-map", newRequest(addr10, withURL("/admin/login")), 0, "URL-MAP mismatch"},

		{"expr-url-suffix-set", newRequest(addr10, withURL("/foo/bar.tar.gz")), 1, "URL-SUFFIX-SET mismatch"},
		{"expr-url-suffix-set", newRequest(addr10, withURL("/foo/bar.zip")), 1, "URL-SUFFIX-SET mismatch"},
		{"expr-url-suffix-set", newRequest(addr10, withURL("/foo/bar.db")), 1, "URL-SUFFIX-SET mismatch"},
		{"expr-url-suffix-set", newRequest(addr10, withURL("/foo/bar.iso")), 0, "URL-SUFFIX-SET mismatch"},
		{"expr-url-suffix-set", newRequest(addr10, withURL("/foo/bar.gz")), 0, "URL-SUFFIX-SET mismatch"},

		{"expr-url-suffix-map", newRequest(addr10, withURL("/foo/bar.zip")), 1, "URL-SUFFIX-MAP mismatch"},
		{"expr-url-suffix-map", newRequest(addr10, withURL("/foo/bar.iso")), 0, "URL-SUFFIX-MAP mismatch"},
		{"expr-url-suffix-map", newRequest(addr10, withURL("/foo/bar.tar.gz")), 0, "URL-SUFFIX-MAP mismatch"},
		{"expr-url-suffix-map", newRequest(addr10, withURL("/foo/bar.gz")), 1, "URL-SUFFIX-MAP mismatch"},
		{"expr-url-suffix-map", newRequest(addr10, withURL("/foo/bar.xml")), 1, "URL-SUFFIX-MAP mismatch"},
		{"expr-url-suffix-map", newRequest(addr10, withURL("/foo/bar.json")), 1, "URL-SUFFIX-MAP mismatch"},

		{"expr-url-prefix-map", newRequest(addr10, withURL("/admin")), 1, "URL-PREFIX-MAP mismatch"},
		{"expr-url-prefix-map", newRequest(addr10, withURL("/admin/log")), 1, "URL-PREFIX-MAP mismatch"},
		{"expr-url-prefix-map", newRequest(addr10, withURL("/admin/login")), 0, "URL-PREFIX-MAP mismatch"},
		{"expr-url-prefix-map", newRequest(addr10, withURL("/admin/login/foo/bar")), 0, "URL-PREFIX-MAP mismatch"},
		{"expr-url-prefix-map", newRequest(addr10, withURL("/.well-known")), 0, "URL-PREFIX-MAP mismatch"},
		{"expr-url-prefix-map", newRequest(addr10, withURL("/auth")), 1, "URL-PREFIX-MAP mismatch"},
		{"expr-url-prefix-map", newRequest(addr10, withURL("/au")), 0, "URL-PREFIX-MAP mismatch"},
		{"expr-url-prefix-map", newRequest(addr10, withURL("/api")), 1, "URL-PREFIX-MAP mismatch"},
		{"expr-url-prefix-map", newRequest(addr10, withURL("/static/1.jpeg")), 1, "URL-PREFIX-MAP mismatch"},

		// STATUS / STATUS-CLASS
		{"expr-status-class-4xx", newRequest(addr10, withStatus(404)), 1, "STATUS-CLASS 4xx"},
		{"expr-status-class-4xx", newRequest(addr10, withStatus(200)), 0, "STATUS-CLASS 4xx — 200 should not"},
		{"expr-status-404", newRequest(addr10, withStatus(404)), 1, "STATUS 404"},
		{"expr-status-404", newRequest(addr10, withStatus(403)), 0, "STATUS 404 — 403 should not"},

		// HOST
		{"expr-host-exact", newRequest(addr10, withHost("evil.example.com")), 1, "HOST exact"},
		{"expr-host-exact", newRequest(addr10, withHost("good.example.com")), 0, "HOST exact mismatch"},
		{"expr-host-suffix", newRequest(addr10, withHost("foo.bad.net")), 1, "HOST-SUFFIX"},
		{"expr-host-suffix", newRequest(addr10, withHost("good.org")), 0, "HOST-SUFFIX mismatch"},
		{"expr-host-keyword", newRequest(addr10, withHost("xyz-bogus-xyz")), 1, "HOST-KEYWORD"},
		{"expr-host-keyword", newRequest(addr10, withHost("clean")), 0, "HOST-KEYWORD mismatch"},

		// AGENT
		{"expr-agent-exact", newRequest(addr10, withAgent("BadBot/1.0")), 1, "AGENT exact"},
		{"expr-agent-exact", newRequest(addr10, withAgent("GoodBot/1.0")), 0, "AGENT exact mismatch"},
		{"expr-agent-keyword", newRequest(addr10, withAgent("BadBot/2.0")), 1, "AGENT-KEYWORD"},
		{"expr-agent-keyword", newRequest(addr10, withAgent("GoodBot/1.0")), 0, "AGENT-KEYWORD mismatch"},

		{"expr-agent-set", newRequest(addr10, withAgent("GoodBot/1.0")), 0, "AGENT-SET mismatch"},
		{"expr-agent-set", newRequest(addr10, withAgent("BadBot/1.0")), 1, "AGENT-SET mismatch"},
		{"expr-agent-set", newRequest(addr10, withAgent("BadBot")), 1, "AGENT-SET mismatch"},
		{"expr-agent-set", newRequest(addr10, withAgent("Spider")), 1, "AGENT-SET mismatch"},
		{"expr-agent-set", newRequest(addr10, withAgent("Mozilla/5.0")), 1, "AGENT-SET mismatch"},
		{"expr-agent-set", newRequest(addr10, withAgent("Mozilla/5.0 AppleWebKit/537.36")), 0, "AGENT-SET mismatch"},

		// SENT-MORE-THAN / SENT-LESS-THAN
		{"expr-sent-more-than", newRequest(addr10, withSent(50000)), 1, "SENT-MORE-THAN triggered"},
		{"expr-sent-more-than", newRequest(addr10, withSent(500)), 0, "SENT-MORE-THAN not triggered"},
		{"expr-sent-less-than", newRequest(addr10, withSent(512)), 1, "SENT-LESS-THAN triggered"},
		{"expr-sent-less-than", newRequest(addr10, withSent(8192)), 0, "SENT-LESS-THAN not triggered"},

		// TOOK-LONGER-THAN / TOOK-SHORTER-THAN
		{"expr-took-longer-than", newRequest(addr10, withDuration(10*time.Second)), 1, "TOOK-LONGER-THAN"},
		{"expr-took-longer-than", newRequest(addr10, withDuration(1*time.Second)), 0, "TOOK-LONGER-THAN not"},
		{"expr-took-shorter-than", newRequest(addr10, withDuration(10*time.Millisecond)), 1, "TOOK-SHORTER-THAN"},
		{"expr-took-shorter-than", newRequest(addr10, withDuration(500*time.Millisecond)), 0, "TOOK-SHORTER-THAN not"},

		// AND / OR / NOT
		{"expr-and",
			newRequest(addr10, withMethod("POST"), withURL("/api/data")), 1, "AND: both match"},
		{"expr-and",
			newRequest(addr10, withMethod("GET"), withURL("/api/data")), 0, "AND: only URL matches"},
		{"expr-or",
			newRequest(addr10, withStatus(404)), 1, "OR: 404 matches"},
		{"expr-or",
			newRequest(addr10, withStatus(500)), 1, "OR: 500 matches"},
		{"expr-or",
			newRequest(addr10, withStatus(200)), 0, "OR: neither matches"},
		{"expr-not",
			newRequest(addr10, withMethod("POST")), 1, "NOT: GET — POST matches"},
		{"expr-not",
			newRequest(addr10, withMethod("GET")), 0, "NOT: GET — GET should not"},

		// CLIENT-IP-CIDR / SERVER-IP-CIDR
		{"expr-client-ip-cidr", newRequest(addr10), 1, "CLIENT-IP-CIDR: 10.0.0.5 in 10.0.0.0/8"},
		{"expr-client-ip-cidr", newRequest(addr99), 0, "CLIENT-IP-CIDR: 99.99.99.99 not in 10.0.0.0/8"},
		{"expr-server-ip-cidr", newRequest(addr10, withServer(addr172)), 1, "SERVER-IP-CIDR: 172.16.0.1 in 172.16.0.0/12"},
		{"expr-server-ip-cidr", newRequest(addr10, withServer(netip.MustParseAddr("10.0.0.1"))), 0, "SERVER-IP-CIDR: 10.0.0.1 not in 172.16.0.0/12"},

		// BEFORE / AFTER
		{"expr-before", newRequest(addr10, withTime(baseTime.Add(-1*time.Hour))), 1, "BEFORE: time before 2025-01-01"},
		{"expr-before", newRequest(addr10, withTime(baseTime)), 0, "BEFORE: time after 2025-01-01"},
		{"expr-after", newRequest(addr10, withTime(baseTime)), 0, "AFTER: time after 2025-01-01"},
		{"expr-after", newRequest(addr10, withTime(time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC))), 0, "AFTER: time before 2025-01-01"},
	}

	for _, tt := range tests {
		t.Run(tt.desc, func(t *testing.T) {
			jail.bans = jail.bans[:0]

			// channel is now engine-owned
			re := New(
				WithJail(jail),
				WithFileSizeIndex(fsi),
				WithCache(cache.NewCCacheCache(100)),
				WithNumWorkers(1),
			)

			cfg := renameMainTo(chains, tt.chainName)
			if err := re.Start(cfg); err != nil {
				t.Fatalf("Start: %v", err)
			}
			defer re.Shutdown()

			re.SendChan() <- tt.req
			time.Sleep(10 * time.Millisecond)

			if got := jail.banCount(); got != tt.wantBans {
				t.Errorf("bans: got %d, want %d", got, tt.wantBans)
			}
		})
	}
}

// --------------- tests: bucket behavior ---------------

func TestBucketBehavior(t *testing.T) {
	jail := newStubJail()
	fsi := newStubFileSizeIndex(map[string]int64{
		"/file1.zip": 1000,
	})
	// Setup for file-ratio bucket
	fsi.sizes["test/data.txt"] = 2000 // file size for ratio

	chains := readYAMLChains(t, "testdata/bucket.yaml")
	addr1 := netip.MustParseAddr("10.0.0.1")

	baseTime := time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC)

	t.Run("byte bucket overflow on second request", func(t *testing.T) {
		jail.bans = jail.bans[:0]
		// channel is now engine-owned
		re := New(
			WithJail(jail),
			WithFileSizeIndex(fsi),
			WithCache(cache.NewCCacheCache(100)),
			WithNumWorkers(1),
		)
		cfg := renameMainTo(chains, "bucket-byte")
		if err := re.Start(cfg); err != nil {
			t.Fatalf("Start: %v", err)
		}
		defer re.Shutdown()

		// First request: byte count 2000 > volume 1024 -> immediate ban
		req1 := newRequest(addr1, withSent(2000))
		re.SendChan() <- req1
		time.Sleep(100 * time.Millisecond)

		if got := jail.banCount(); got != 1 {
			t.Errorf("first request: expected 1 ban, got %d", got)
		}
	})

	t.Run("freq bucket overflow on third request", func(t *testing.T) {
		jail.bans = jail.bans[:0]
		// channel is now engine-owned
		re := New(
			WithJail(jail),
			WithFileSizeIndex(fsi),
			WithCache(cache.NewCCacheCache(100)),
			WithNumWorkers(1),
		)
		cfg := renameMainTo(chains, "bucket-freq")
		if err := re.Start(cfg); err != nil {
			t.Fatalf("Start: %v", err)
		}
		defer re.Shutdown()

		// Requests 1 and 2: should not trigger (<=2 volume)
		req := newRequest(addr1)
		re.SendChan() <- req
		time.Sleep(50 * time.Millisecond)
		if got := jail.banCount(); got != 0 {
			t.Errorf("after 1st request: expected 0 bans, got %d", got)
		}

		re.SendChan() <- req
		time.Sleep(50 * time.Millisecond)
		if got := jail.banCount(); got != 0 {
			t.Errorf("after 2nd request: expected 0 bans, got %d", got)
		}

		// Request 3: exceeds volume of 2
		re.SendChan() <- req
		time.Sleep(100 * time.Millisecond)
		if got := jail.banCount(); got != 1 {
			t.Errorf("after 3rd request: expected 1 ban, got %d", got)
		}
	})

	t.Run("file ratio bucket", func(t *testing.T) {
		jail.bans = jail.bans[:0]
		// channel is now engine-owned
		re := New(
			WithJail(jail),
			WithFileSizeIndex(fsi),
			WithCache(cache.NewCCacheCache(100)),
			WithNumWorkers(1),
		)
		cfg := renameMainTo(chains, "bucket-file-ratio")
		if err := re.Start(cfg); err != nil {
			t.Fatalf("Start: %v", err)
		}
		defer re.Shutdown()

		// First request: sent=100, ratio=100/1000=0.1 -> don't ban
		req := newRequest(addr1, withSent(100), withURL("/file1.zip"))
		re.SendChan() <- req
		time.Sleep(50 * time.Millisecond)
		if got := jail.banCount(); got != 0 {
			t.Errorf("first request: expected 0 ban, got %d", got)
		}

		// Second request: sent=100, ratio=200/1000=0.2 -> don't ban
		re.SendChan() <- req
		time.Sleep(50 * time.Millisecond)
		if got := jail.banCount(); got != 0 {
			t.Errorf("second request: expected 0 ban, got %d", got)
		}

		// Third request: sent=100, ratio=300/1000=0.3 -> don't ban
		re.SendChan() <- req
		time.Sleep(50 * time.Millisecond)
		if got := jail.banCount(); got != 0 {
			t.Errorf("third request: expected 0 ban, got %d", got)
		}

		// Forth request: sent=100, ratio=400/1000=0.4 -> don't ban
		re.SendChan() <- req
		time.Sleep(50 * time.Millisecond)
		if got := jail.banCount(); got != 0 {
			t.Errorf("forth request: expected 0 ban, got %d", got)
		}

		// Fifth request: sent=101, ratio=501/1000=0.501 -> ban
		req = newRequest(addr1, withSent(101), withURL("/file1.zip"))
		re.SendChan() <- req
		time.Sleep(50 * time.Millisecond)
		if got := jail.banCount(); got != 1 {
			t.Errorf("fifth request: expected 1 ban, got %d", got)
		}
	})

	t.Run("byte bucket less than leak", func(t *testing.T) {
		jail.bans = jail.bans[:0]
		// channel is now engine-owned
		re := New(
			WithJail(jail),
			WithFileSizeIndex(fsi),
			WithCache(cache.NewCCacheCache(100)),
			WithNumWorkers(1),
		)
		cfg := renameMainTo(chains, "bucket-byte-leak")
		if err := re.Start(cfg); err != nil {
			t.Fatalf("Start: %v", err)
		}
		defer re.Shutdown()

		for i := range 10000 {
			req := newRequest(addr1, withSent(500), withTime(baseTime.Add(time.Duration(i)*time.Second)))
			re.SendChan() <- req
			if got := jail.banCount(); got != 0 {
				t.Errorf("expected 0 ban, got %d", got)
			}
		}
	})

	t.Run("byte bucket more than leak", func(t *testing.T) {
		jail.bans = jail.bans[:0]
		// channel is now engine-owned
		re := New(
			WithJail(jail),
			WithFileSizeIndex(fsi),
			WithCache(cache.NewCCacheCache(100)),
			WithNumWorkers(1),
		)
		cfg := renameMainTo(chains, "bucket-byte-leak")
		if err := re.Start(cfg); err != nil {
			t.Fatalf("Start: %v", err)
		}
		defer re.Shutdown()

		for i := range 10000 {
			req := newRequest(addr1, withSent(512+30), withTime(baseTime.Add(time.Duration(i)*time.Second)))
			re.SendChan() <- req
			if got := jail.banCount(); got >= 1 {
				return
			}
		}

		t.Errorf("expected to be banned")
	})

	t.Run("freq bucket less than leak", func(t *testing.T) {
		jail.bans = jail.bans[:0]
		// channel is now engine-owned
		re := New(
			WithJail(jail),
			WithFileSizeIndex(fsi),
			WithCache(cache.NewCCacheCache(100)),
			WithNumWorkers(1),
		)
		cfg := renameMainTo(chains, "bucket-freq-leak")
		if err := re.Start(cfg); err != nil {
			t.Fatalf("Start: %v", err)
		}
		defer re.Shutdown()

		for i := range 10000 {
			req := newRequest(addr1, withTime(baseTime.Add(time.Duration(i*2)*time.Second)))
			re.SendChan() <- req
			if got := jail.banCount(); got >= 1 {
				t.Errorf("shouldn't be banned")
			}
		}
	})

	t.Run("freq bucket more than leak", func(t *testing.T) {
		jail.bans = jail.bans[:0]
		// channel is now engine-owned
		re := New(
			WithJail(jail),
			WithFileSizeIndex(fsi),
			WithCache(cache.NewCCacheCache(100)),
			WithNumWorkers(1),
		)
		cfg := renameMainTo(chains, "bucket-freq-leak")
		if err := re.Start(cfg); err != nil {
			t.Fatalf("Start: %v", err)
		}
		defer re.Shutdown()

		for i := range 10000 {
			req := newRequest(addr1, withTime(baseTime.Add(time.Duration(i)*time.Second)))
			re.SendChan() <- req
			re.SendChan() <- req
			if got := jail.banCount(); got >= 1 {
				return
			}
		}

		t.Errorf("expected to be banned")
	})

	t.Run("file ratio bucket less than leak", func(t *testing.T) {
		jail.bans = jail.bans[:0]
		// channel is now engine-owned
		re := New(
			WithJail(jail),
			WithFileSizeIndex(fsi),
			WithCache(cache.NewCCacheCache(100)),
			WithNumWorkers(1),
		)
		cfg := renameMainTo(chains, "bucket-file-ratio-leak")
		if err := re.Start(cfg); err != nil {
			t.Fatalf("Start: %v", err)
		}
		defer re.Shutdown()

		for i := range 10000 {
			req := newRequest(addr1, withTime(baseTime.Add(time.Duration(i)*time.Second)), withSent(50), withURL("/file1.zip"))
			re.SendChan() <- req
			if got := jail.banCount(); got >= 1 {
				t.Errorf("shouldn't be banned")
			}
		}
	})

	t.Run("file ratio bucket more than leak", func(t *testing.T) {
		jail.bans = jail.bans[:0]
		// channel is now engine-owned
		re := New(
			WithJail(jail),
			WithFileSizeIndex(fsi),
			WithCache(cache.NewCCacheCache(100)),
			WithNumWorkers(1),
		)
		cfg := renameMainTo(chains, "bucket-file-ratio-leak")
		if err := re.Start(cfg); err != nil {
			t.Fatalf("Start: %v", err)
		}
		defer re.Shutdown()

		for i := range 10000 {
			req := newRequest(addr1, withTime(baseTime.Add(time.Duration(i)*time.Second)), withSent(1000), withURL("/file1.zip"))
			re.SendChan() <- req
			re.SendChan() <- req
			if got := jail.banCount(); got >= 1 {
				return
			}
		}

		t.Errorf("expected to be banned")
	})
}

// --------------- tests: ban and log statements ---------------

func TestBanAndLogStatements(t *testing.T) {
	jail := newStubJail()
	fsi := newStubFileSizeIndex(map[string]int64{})
	addr1 := netip.MustParseAddr("10.0.0.1")

	chains := readYAMLChains(t, "testdata/ban_log.yaml")

	t.Run("BAN duration 30m", func(t *testing.T) {
		jail.bans = jail.bans[:0]
		// channel is now engine-owned
		re := New(
			WithJail(jail),
			WithFileSizeIndex(fsi),
			WithCache(cache.NewCCacheCache(100)),
			WithNumWorkers(1),
		)
		cfg := renameMainTo(chains, "ban-30m")
		if err := re.Start(cfg); err != nil {
			t.Fatalf("Start: %v", err)
		}
		defer re.Shutdown()

		re.SendChan() <- newRequest(addr1)
		time.Sleep(100 * time.Millisecond)

		if got := jail.banCount(); got != 1 {
			t.Errorf("expected 1 ban, got %d", got)
		}
		lb := jail.lastBan()
		d := time.Until(lb.ExpiresAt)
		if d < 29*time.Minute || d > 31*time.Minute {
			t.Errorf("expected ~30m ban, got %v", d)
		}
	})

	t.Run("BAN duration 2h", func(t *testing.T) {
		jail.bans = jail.bans[:0]
		// channel is now engine-owned
		re := New(
			WithJail(jail),
			WithFileSizeIndex(fsi),
			WithCache(cache.NewCCacheCache(100)),
			WithNumWorkers(1),
		)
		cfg := renameMainTo(chains, "ban-2h")
		if err := re.Start(cfg); err != nil {
			t.Errorf("Start: %v", err)
		}
		defer re.Shutdown()

		re.SendChan() <- newRequest(addr1)
		time.Sleep(100 * time.Millisecond)

		if got := jail.banCount(); got != 1 {
			t.Errorf("expected 1 ban, got %d", got)
		}
		lb := jail.lastBan()
		d := time.Until(lb.ExpiresAt)
		if d < 119*time.Minute || d > 121*time.Minute {
			t.Errorf("expected ~2h ban, got %v", d)
		}
	})

	t.Run("BAN duration 1h30m", func(t *testing.T) {
		jail.bans = jail.bans[:0]
		// channel is now engine-owned
		re := New(
			WithJail(jail),
			WithFileSizeIndex(fsi),
			WithCache(cache.NewCCacheCache(100)),
			WithNumWorkers(1),
		)
		cfg := renameMainTo(chains, "ban-90m")
		if err := re.Start(cfg); err != nil {
			t.Fatalf("Start: %v", err)
		}
		defer re.Shutdown()

		re.SendChan() <- newRequest(addr1)
		time.Sleep(100 * time.Millisecond)

		if got := jail.banCount(); got != 1 {
			t.Errorf("expected 1 ban, got %d", got)
		}
		lb := jail.lastBan()
		d := time.Until(lb.ExpiresAt)
		if d < 89*time.Minute || d > 91*time.Minute {
			t.Errorf("expected ~90m ban, got %v", d)
		}
	})

	t.Run("LOG at various levels", func(t *testing.T) {
		var buf bytes.Buffer
		h := slog.NewJSONHandler(&buf, &slog.HandlerOptions{Level: slog.LevelDebug})
		logger := slog.New(h)

		levels := []struct {
			chain string
			text  string
		}{
			{"log-debug", "DEBUG_TEST"},
			{"log-info", "INFO_TEST"},
			{"log-warn", "WARN_TEST"},
			{"log-error", "ERROR_TEST"},
		}

		for _, lv := range levels {
			t.Run(lv.text, func(t *testing.T) {
				buf.Reset()
				// channel is now engine-owned
				re := New(
					WithJail(jail),
					WithFileSizeIndex(fsi),
					WithCache(cache.NewCCacheCache(100)),
					WithLogger(logger),
					WithNumWorkers(1),
				)
				cfg := renameMainTo(chains, lv.chain)
				if err := re.Start(cfg); err != nil {
					t.Fatalf("Start: %v", err)
				}
				defer re.Shutdown()

				re.SendChan() <- newRequest(addr1)
				time.Sleep(100 * time.Millisecond)

				if !bytes.Contains(buf.Bytes(), []byte(lv.text)) {
					t.Errorf("log output missing %q: %s", lv.text, buf.String())
				}
			})
		}
	})

	t.Run("BAN is terminal; subsequent LOG not fired", func(t *testing.T) {
		var buf bytes.Buffer
		h := slog.NewJSONHandler(&buf, &slog.HandlerOptions{Level: slog.LevelDebug})
		logger := slog.New(h)

		jail.bans = jail.bans[:0]
		// channel is now engine-owned
		re := New(
			WithJail(jail),
			WithFileSizeIndex(fsi),
			WithCache(cache.NewCCacheCache(100)),
			WithLogger(logger),
			WithNumWorkers(1),
		)
		cfg := renameMainTo(chains, "ban-then-log")
		if err := re.Start(cfg); err != nil {
			t.Fatalf("Start: %v", err)
		}
		defer re.Shutdown()

		re.SendChan() <- newRequest(addr1)
		time.Sleep(100 * time.Millisecond)

		if got := jail.banCount(); got != 1 {
			t.Errorf("expected 1 ban, got %d", got)
		}
		if bytes.Contains(buf.Bytes(), []byte("BAN_DID_NOT_STOP")) {
			t.Error("LOG after BAN should not have fired")
		}
	})

	t.Run("LOG then BAN — both fire", func(t *testing.T) {
		var buf bytes.Buffer
		h := slog.NewJSONHandler(&buf, &slog.HandlerOptions{Level: slog.LevelDebug})
		logger := slog.New(h)

		jail.bans = jail.bans[:0]
		// channel is now engine-owned
		re := New(
			WithJail(jail),
			WithFileSizeIndex(fsi),
			WithCache(cache.NewCCacheCache(100)),
			WithLogger(logger),
			WithNumWorkers(1),
		)
		cfg := renameMainTo(chains, "log-then-ban")
		if err := re.Start(cfg); err != nil {
			t.Fatalf("Start: %v", err)
		}
		defer re.Shutdown()

		re.SendChan() <- newRequest(addr1)
		time.Sleep(100 * time.Millisecond)

		if !bytes.Contains(buf.Bytes(), []byte("LOG_PRECEDES_BAN")) {
			t.Errorf("LOG didn't fire: %s", buf.String())
		}
		if got := jail.banCount(); got != 1 {
			t.Errorf("expected 1 ban, got %d", got)
		}
	})
}

// --------------- functional-option helpers ---------------

func withMethod(m string) func(*dto.Request) {
	return func(r *dto.Request) { r.Method = m }
}

func withURL(u string) func(*dto.Request) {
	return func(r *dto.Request) { r.URL = u }
}

func withStatus(s int) func(*dto.Request) {
	return func(r *dto.Request) { r.Status = s }
}

func withHost(h string) func(*dto.Request) {
	return func(r *dto.Request) { r.Host = h }
}

func withAgent(a string) func(*dto.Request) {
	return func(r *dto.Request) { r.Agent = a }
}

func withSent(s int64) func(*dto.Request) {
	return func(r *dto.Request) { r.Sent = s }
}

func withDuration(d time.Duration) func(*dto.Request) {
	return func(r *dto.Request) { r.Duration = d }
}

func withTime(t time.Time) func(*dto.Request) {
	return func(r *dto.Request) { r.Time = t }
}

func withServer(ip netip.Addr) func(*dto.Request) {
	return func(r *dto.Request) { r.Server = ip }
}
