/*
LLM usage: this test file was generated by deepseek-v4-pro with manual modifications.
*/
package cache

import (
	"testing"
	"time"
)

// ---------- TestCCacheCache_GetSet ----------

func TestCCacheCache_GetSet(t *testing.T) {
	c := NewCCacheCache(100)

	tests := []struct {
		name   string
		bucket string
		key    string
		entry  CacheEntry
	}{
		{
			name:   "basic entry",
			bucket: "b1",
			key:    "k1",
			entry:  CacheEntry{LastUpdate: 100, Value: 42},
		},
		{
			name:   "zero value",
			bucket: "b1",
			key:    "k2",
			entry:  CacheEntry{LastUpdate: 0, Value: 0},
		},
		{
			name:   "different bucket same key",
			bucket: "b2",
			key:    "k1",
			entry:  CacheEntry{LastUpdate: 200, Value: 99},
		},
		{
			name:   "large values",
			bucket: "b3",
			key:    "large",
			entry:  CacheEntry{LastUpdate: 1<<62 - 1, Value: 1<<64 - 1},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			c.Set(tt.bucket, tt.key, tt.entry, time.Hour)

			got, ok := c.Get(tt.bucket, tt.key)
			if !ok {
				t.Fatalf("Get(%q, %q): ok=false, want true", tt.bucket, tt.key)
			}
			if got != tt.entry {
				t.Errorf("Get(%q, %q) = %+v, want %+v", tt.bucket, tt.key, got, tt.entry)
			}
		})
	}
}

// ---------- TestCCacheCache_Get_NotFound ----------

func TestCCacheCache_Get_NotFound(t *testing.T) {
	c := NewCCacheCache(100)

	tests := []struct {
		name   string
		bucket string
		key    string
	}{
		{name: "empty cache", bucket: "b", key: "k"},
		{name: "nonexistent bucket", bucket: "nobucket", key: "k"},
		{name: "existing bucket wrong key", bucket: "b", key: "missing"},
	}

	// pre-populate one entry so we can test "wrong key in existing bucket"
	c.Set("b", "exists", CacheEntry{LastUpdate: 1, Value: 1}, time.Hour)

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, ok := c.Get(tt.bucket, tt.key)
			if ok {
				t.Errorf("Get(%q, %q): ok=true, want false; got=%+v", tt.bucket, tt.key, got)
			}
		})
	}
}

// ---------- TestCCacheCache_Iterator ----------

func TestCCacheCache_Iterator(t *testing.T) {
	c := NewCCacheCache(100)

	entries := map[string]CacheEntry{
		"a": {LastUpdate: 1, Value: 10},
		"b": {LastUpdate: 2, Value: 20},
		"c": {LastUpdate: 3, Value: 30},
	}
	for k, v := range entries {
		c.Set("bucket", k, v, time.Hour)
	}

	// collect all entries from the iterator
	collected := make(map[string]CacheEntry)
	for k, v := range c.Iterator("bucket") {
		collected[k] = v
	}

	if len(collected) != len(entries) {
		t.Fatalf("iterator yielded %d entries, want %d", len(collected), len(entries))
	}
	for k, want := range entries {
		got, ok := collected[k]
		if !ok {
			t.Errorf("iterator: missing key %q", k)
			continue
		}
		if got != want {
			t.Errorf("iterator[%q] = %+v, want %+v", k, got, want)
		}
	}
}

func TestCCacheCache_Iterator_Empty(t *testing.T) {
	c := NewCCacheCache(100)

	for k, v := range c.Iterator("nonexistent") {
		t.Errorf("empty iterator yielded (%q, %+v), want nothing", k, v)
	}
}

func TestCCacheCache_Iterator_EarlyStop(t *testing.T) {
	c := NewCCacheCache(100)

	for i := 0; i < 5; i++ {
		c.Set("b", string(rune('a'+i)), CacheEntry{Value: uint64(i)}, time.Hour)
	}

	count := 0
	for range c.Iterator("b") {
		count++
		if count >= 2 {
			// Stop early; ForEachFunc returns false when yield returns false
			break
		}
	}
	// we stopped after 2, so we should not have iterated all 5
	if count != 2 {
		t.Errorf("early stop count = %d, want 2", count)
	}
}

// ---------- TestCCacheCache_TTLExpiry ----------

func TestCCacheCache_TTLExpiry(t *testing.T) {
	c := NewCCacheCache(100)

	c.Set("b", "expires", CacheEntry{LastUpdate: 1, Value: 99}, 10*time.Millisecond)

	// should be available immediately
	got, ok := c.Get("b", "expires")
	if !ok || got.Value != 99 {
		t.Fatalf("immediate Get: ok=%v, got=%+v, want ok=true with Value=99", ok, got)
	}

	// wait for TTL to pass (plus some buffer for internal cleanup)
	time.Sleep(50 * time.Millisecond)

	got, ok = c.Get("b", "expires")
	if ok {
		t.Errorf("Get after TTL: ok=true, want false; got=%+v", got)
	}

	// iterator should not yield the expired entry
	for k, v := range c.Iterator("b") {
		t.Errorf("iterator yielded expired entry: %q => %+v", k, v)
	}
}

func TestCCacheCache_TTLExpiry_NotExpired(t *testing.T) {
	c := NewCCacheCache(100)

	c.Set("b", "fresh", CacheEntry{Value: 7}, 10*time.Second)
	time.Sleep(10 * time.Millisecond)

	got, ok := c.Get("b", "fresh")
	if !ok {
		t.Error("Get should succeed before TTL elapses")
	}
	if got.Value != 7 {
		t.Errorf("Get Value = %d, want 7", got.Value)
	}
}

// ---------- TestCCacheCache_MaxSizeEviction ----------

func TestCCacheCache_MaxSizeEviction(t *testing.T) {
	// small cache: max 2 items total
	c := NewCCacheCache(2)

	// insert many entries to force eviction, then verify total count ≤ MaxSize
	for i := 0; i < 10; i++ {
		c.Set("b", string(rune('a'+i)), CacheEntry{Value: uint64(i)}, time.Hour)
	}

	// Give the background eviction worker a moment
	time.Sleep(5 * time.Millisecond)

	// Count items via iterator — should be at most MaxSize
	count := 0
	for range c.Iterator("b") {
		count++
	}
	if count > 2 {
		t.Errorf("iterator count = %d, want ≤ 2 (MaxSize eviction)", count)
	}
	if count == 0 {
		t.Error("iterator count = 0, cache is unexpectedly empty")
	}
}

func TestCCacheCache_MaxSizeEviction_DifferentBuckets(t *testing.T) {
	// max 2 items per bucket — different buckets have independent limits
	c := NewCCacheCache(2)

	c.Set("b1", "k1", CacheEntry{Value: 1}, time.Hour)
	c.Set("b1", "k2", CacheEntry{Value: 2}, time.Hour)
	c.Set("b2", "k1", CacheEntry{Value: 3}, time.Hour)
	c.Set("b2", "k2", CacheEntry{Value: 4}, time.Hour)

	// both buckets hold 2 items each — no eviction should have occurred
	for _, bucket := range []string{"b1", "b2"} {
		for _, key := range []string{"k1", "k2"} {
			if _, ok := c.Get(bucket, key); !ok {
				t.Errorf("bucket %q key %q: Get returned ok=false, want true", bucket, key)
			}
		}
	}
}

// ---------- TestCCacheCache_GetSet_Overwrite ----------

func TestCCacheCache_GetSet_Overwrite(t *testing.T) {
	c := NewCCacheCache(100)

	c.Set("b", "k", CacheEntry{LastUpdate: 1, Value: 100}, time.Hour)
	c.Set("b", "k", CacheEntry{LastUpdate: 2, Value: 200}, time.Hour)

	got, ok := c.Get("b", "k")
	if !ok {
		t.Fatal("Get returned ok=false after overwrite")
	}
	if got.Value != 200 || got.LastUpdate != 2 {
		t.Errorf("Get = %+v, want {LastUpdate:2 Value:200}", got)
	}
}

// ---------- Race detection ----------

func TestCCacheCache_ConcurrentAccess(t *testing.T) {
	c := NewCCacheCache(100)
	done := make(chan struct{})

	go func() {
		for i := 0; i < 100; i++ {
			c.Set("b", "k", CacheEntry{Value: uint64(i)}, time.Hour)
			c.Get("b", "k")
		}
		done <- struct{}{}
	}()
	go func() {
		for i := 0; i < 100; i++ {
			c.Set("b", "k", CacheEntry{Value: uint64(i)}, time.Hour)
			c.Get("b", "k")
		}
		done <- struct{}{}
	}()
	<-done
	<-done
}

// ---------- Statistics ----------

func TestCCacheCache_Statistics_Initial(t *testing.T) {
	c := NewCCacheCache(100)
	s := c.Statistics()
	if s.Gets != 0 || s.Sets != 0 || s.Misses != 0 || s.Size != 0 {
		t.Errorf("initial stats should be all zero: %+v", s)
	}
}

func TestCCacheCache_Statistics_Sets(t *testing.T) {
	c := NewCCacheCache(100)

	c.Set("b", "k1", CacheEntry{Value: 1}, time.Hour)
	c.Set("b", "k2", CacheEntry{Value: 2}, time.Hour)
	c.Set("b", "k3", CacheEntry{Value: 3}, time.Hour)

	s := c.Statistics()
	if s.Sets != 3 {
		t.Errorf("Sets = %d, want 3", s.Sets)
	}
	if s.Size != 3 {
		t.Errorf("Size = %d, want 3", s.Size)
	}
	if s.Gets != 0 {
		t.Errorf("Gets = %d, want 0 (only Sets performed)", s.Gets)
	}
}

func TestCCacheCache_Statistics_GetsHits(t *testing.T) {
	c := NewCCacheCache(100)
	c.Set("b", "k", CacheEntry{Value: 42}, time.Hour)

	// hit
	c.Get("b", "k")
	// hit again
	c.Get("b", "k")

	s := c.Statistics()
	if s.Gets != 2 {
		t.Errorf("Gets = %d, want 2", s.Gets)
	}
	if s.Misses != 0 {
		t.Errorf("Misses = %d, want 0", s.Misses)
	}
}

func TestCCacheCache_Statistics_GetsMisses(t *testing.T) {
	c := NewCCacheCache(100)

	// miss on empty cache
	c.Get("b", "missing")
	// miss on wrong key
	c.Set("b", "exists", CacheEntry{Value: 1}, time.Hour)
	c.Get("b", "wrong")

	s := c.Statistics()
	if s.Gets != 2 {
		t.Errorf("Gets = %d, want 2", s.Gets)
	}
	if s.Misses != 2 {
		t.Errorf("Misses = %d, want 2", s.Misses)
	}
	// one Set
	if s.Sets != 1 {
		t.Errorf("Sets = %d, want 1", s.Sets)
	}
}

func TestCCacheCache_Statistics_Overwrite(t *testing.T) {
	c := NewCCacheCache(100)

	c.Set("b", "k", CacheEntry{Value: 1}, time.Hour)
	c.Set("b", "k", CacheEntry{Value: 2}, time.Hour)
	c.Set("b", "k", CacheEntry{Value: 3}, time.Hour)

	s := c.Statistics()
	if s.Sets != 3 {
		t.Errorf("Sets = %d, want 3 (each Set counts)", s.Sets)
	}
	// overwriting the same key should keep Size at 1
	if s.Size != 1 {
		t.Errorf("Size = %d, want 1 (same key overwritten)", s.Size)
	}
}

func TestCCacheCache_Statistics_Evictions(t *testing.T) {
	c := NewCCacheCache(2)

	for i := 0; i < 10; i++ {
		c.Set("b", string(rune('a'+i)), CacheEntry{Value: uint64(i)}, time.Hour)
	}
	time.Sleep(5 * time.Millisecond)

	s := c.Statistics()
	if s.Sets != 10 {
		t.Errorf("Sets = %d, want 10", s.Sets)
	}
	if s.Evictions <= 0 {
		t.Errorf("Evictions = %d, want > 0 (MaxSize enforcement)", s.Evictions)
	}
	if s.Size > 2 {
		t.Errorf("Size = %d, want ≤ 2", s.Size)
	}
}

func TestCCacheCache_Statistics_TTLExpired(t *testing.T) {
	c := NewCCacheCache(100)

	c.Set("b", "exp", CacheEntry{Value: 99}, 10*time.Millisecond)

	// hit before expiry
	c.Get("b", "exp")

	time.Sleep(50 * time.Millisecond)

	// miss after expiry
	c.Get("b", "exp")

	s := c.Statistics()
	if s.Gets != 2 {
		t.Errorf("Gets = %d, want 2", s.Gets)
	}
	if s.Misses != 1 {
		t.Errorf("Misses = %d, want 1 (TTL expiry)", s.Misses)
	}
}

func TestCCacheCache_Statistics_MultipleBuckets(t *testing.T) {
	c := NewCCacheCache(100)

	c.Set("b1", "k1", CacheEntry{Value: 1}, time.Hour)
	c.Set("b1", "k2", CacheEntry{Value: 2}, time.Hour)
	c.Set("b2", "k1", CacheEntry{Value: 3}, time.Hour)

	c.Get("b1", "k1") // hit
	c.Get("b1", "k3") // miss
	c.Get("b2", "k1") // hit
	c.Get("b2", "k9") // miss

	s := c.Statistics()
	if s.Sets != 3 {
		t.Errorf("Sets = %d, want 3", s.Sets)
	}
	if s.Gets != 4 {
		t.Errorf("Gets = %d, want 4", s.Gets)
	}
	if s.Misses != 2 {
		t.Errorf("Misses = %d, want 2", s.Misses)
	}
	if s.Size != 3 {
		t.Errorf("Size = %d, want 3 (2 in b1 + 1 in b2)", s.Size)
	}
}
